import type { Metadata } from "next";
import { Roboto, Sofia } from "next/font/google";
import "./css/globals.css";
import "./css/lineAnimation.css";
import "./css/loader.css";
import "./css/humMenu.css";
import "./css/typeHead.css";
import "./css/swiper.css";
import Layout from "@/components/layout/Layout";
import { ApolloWrapper } from "./providers";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--roboto",
  display: "swap",
});
const font1 = Sofia({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font1",
  display: "swap",
});

export const metadata: Metadata = {
  title: "News",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  authModal,
}: Readonly<{
  children: React.ReactNode;
  authModal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${font1.variable} relative scroll-smooth bg-slate-50 antialiased`}
      >
        <ApolloWrapper>
          <Layout header={1} footer={1}>
            {/*  modal portal */}
            <div id="modal-portal" className="relative z-[999999]" />
            {/*  auth modal */}
            {authModal ? authModal : "null"}
            {children}
          </Layout>
        </ApolloWrapper>
      </body>
    </html>
  );
}
